version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: nhommtl/mysql1-sneaker-store:latest
    # volumes:
    #   - ./data:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: always
    command: ["mysqld"]

  express-app:
    container_name: express-app
    image: nhommtl/express1-sneaker-store:latest
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: abc123
      DB_DATABASE: sneakerstore
      BASE_URL: $localhost:3001
      LOCAL_HOST: $localhost
      REACT_CORS: $localhost:3000
    ports:
      - "3001:3001"
    networks:
      - backend
    restart: always
    command: ["sh", "-c", "sleep 50 && npm start"]
  react-app:
    container_name: react-app
    image: nhommtl/reactjs-sneaker-store:latest
    depends_on:
      - express-app
    environment:
      REACT_APP_API_URL: $localhost:3001
    ports:
      - "3000:3000"
    networks:
      - backend
      # - frontent
    restart: always
    command: ["sh", "-c", "sleep 55 && npm start"]


networks:
  backend:
    driver: bridge
  frontend:
